# Generated by Django 4.1.1 on 2022-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_cigna_data_wave_3_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cigna_data',
            name='Choice1C_CE_Selected_Individual_Mari_805',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cigna_data',
            name='ORDER_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cigna_data',
            name='SEQUENCE_NO',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cigna_data',
            name='Wave_1_OMD_Creative_Code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
