    # df = pd.read_csv('Data_feb_84.txt',sep=',')
    # for i in range(100):     
    #     l = [list(df['SEQUENCE NO'])[i],
    #                     list(df['ORDER ID'])[i],
    #                     list(df['LIST ID'])[i],
    #                     list(df['ULTIMATE DUNS NUMBER'])[i],
    #                     list(df['Choice1A Decile'])[i],
    #                     list(df['Choice1A p 1'])[i],
    #                     list(df['Choice1B p sp'])[i],
    #                     list(df['Choice1C P 1'])[i],
    #                     list(df['Choice1C Decile'])[i],
    #                     list(df['Choice1C CE Selected Individual Mari 805'])[i],
    #                     list(df['BH MedResp resp decile'])[i],
    #                     list(df['BH MedResp filler1'])[i],
    #                     list(df['BH MedResp P resp'])[i],
    #                     list(df['BH MedResp filler2'])[i],
    #                     list(df['Opt P Enroll backend target1'])[i],
    #                     list(df['Opt P Enroll prop target1'])[i],
    #                     list(df['Opt Enroll backend decile'])[i],
    #                     list(df['Opt Enroll prop decile'])[i],
    #                     list(df['Segmentation into'])[i],
    #                     list(df['MZP Individual ID'])[i],
    #                     list(df['MZP Household ID'])[i],
    #                     list(df['Control'])[i],
    #                     list(df['Wave 1 OMD'])[i],
    #                     list(df['Wave 1 OMD Creative Code'])[i],
    #                     list(df['Wave 1 OMD Code on Mail'])[i],
    #                     list(df['Wave 2 OMD'])[i],
    #                     list(df['Wave 2 OMD Creative Code'])[i],
    #                     list(df['Wave 2 OMD Code on Mail'])[i],
    #                     list(df['Wave 3 OMD'])[i],
    #                     list(df['Wave 4 OMD Creative Code'])[i],
    #                     list(df['Wave 4 OMD Code on Mail'])[i],
    #                     list(df['Wave 4 OMD'])[i],
    #                     list(df['Wave 3 OMD Creative Code'])[i],
    #                     list(df['Wave 3 OMD Code on Mail'])[i],
    #                     list(df['Wave 1 Mail'])[i],
    #                     list(df['Wave 1 Mail Creative Code'])[i],
    #                     list(df['Wave 1 Mail Code on Mail'])[i],
    #                     list(df['Wave 1 Email'])[i],
    #                     list(df['Wave 1 Email Creative Code'])[i],
    #                     list(df['Wave 1 Email Code on Mail'])[i],
    #                     list(df['Wave 1 Email Deliverability Indicator'])[i],
    #                     list(df['Wave 1 Email Open'])[i],
    #                     list(df['Wave 1 Email Click'])[i],
    #                     list(df['Wave 2 Mail'])[i],
    #                     list(df['Wave 2 Mail Creative Code'])[i],
    #                     list(df['Wave 2 Mail Code on Mail'])[i],
    #                     list(df['Wave 2 Email'])[i],
    #                     list(df['Wave 2 Email Creative Code'])[i],
    #                     list(df['Wave 2 Email Code on Mail'])[i],
    #                     list(df['Wave 2 Email Deliverability Indicator'])[i],
    #                     list(df['Wave 2 Email Open'])[i],
    #                     list(df['Wave 2 Email Click'])[i],
    #                     list(df['Wave 3 Mail'])[i],
    #                     list(df['Wave 3 Mail Creative Code'])[i],
    #                     list(df['Wave 3 Mail Code on Mail'])[i],
    #                     list(df['Wave 3 Email'])[i],
    #                     list(df['Wave 3 Email Creative Code'])[i],
    #                     list(df['Wave 3 Email Code on Mail'])[i],
    #                     list(df['Wave 3 Email Deliverability Indicator'])[i],
    #                     list(df['Wave 3 Email Open'])[i],
    #                     list(df['Wave 3 Email Click'])[i],
    #                     list(df['Wave 4 Mail'])[i],
    #                     list(df['Wave 4 Mail Creative Code'])[i],
    #                     list(df['Wave 4 Mail Code on Mail'])[i],
    #                     list(df['Wave 4 Email'])[i],
    #                     list(df['Wave 4 Email Creative Code'])[i],
    #                     list(df['Wave 4 Email Code on Mail'])[i],
    #                     list(df['Wave 4 Email Deliverability Indicator'])[i],
    #                     list(df['Wave 4 Email Open'])[i],
    #                     list(df['Wave 4 Email Click'])[i],
    #                     list(df['Wave 1 Social'])[i],
    #                     list(df['Wave 1 Social Creative Code'])[i],
    #                     list(df['Wave 1 Social Code on Mail'])[i],
    #                     list(df['Wave 2 Social'])[i],
    #                     list(df['Wave 2 Social Creative Code'])[i],
    #                     list(df['Wave 2 Social Code on Mail'])[i],
    #                     list(df['Wave 3 Social'])[i],
    #                     list(df['Wave 3 Social Creative Code'])[i],
    #                     list(df['Wave 3 Social Code on Mail'])[i],
    #                     list(df['Wave 4 Social'])[i],
    #                     list(df['Wave 4 Social Creative Code'])[i],
    #                     list(df['Wave 4 Social Code on Mail'])[i],
    #                     list(df['New Customer Match'])[i],
    #                     list(df['Individual Enterprise ID'])[i],
    #                     list(df['CE Match Level'])[i]]


    #     query = """INSERT INTO dataApp_cigna_data (SEQUENCE_NO,
    #                                         ORDER_ID,
    #                                         LIST_ID,
    #                                         ULTIMATE_DUNS_NUMBER,
    #                                         Choice1A_Decile,
    #                                         Choice1A_p_1,
    #                                         Choice1B_p_sp,
    #                                         Choice1C_P_1,
    #                                         Choice1C_Decile,
    #                                         Choice1C_CE_Selected_Individual_Mari_805,
    #                                         BH_MedResp_resp_decile,
    #                                         BH_MedResp_filler1,
    #                                         BH_MedResp_P_resp,
    #                                         BH_MedResp_filler2,
    #                                         Opt_P_Enroll_backend_target1,
    #                                         Opt_P_Enroll_prop_target1,
    #                                         Opt_Enroll_backend_decile,
    #                                         Opt_Enroll_prop_decile,
    #                                         Segmentation_into,
    #                                         MZP_Individual_ID,
    #                                         MZP_Household_ID,
    #                                         Control,
    #                                         Wave_1_OMD,
    #                                         Wave_1_OMD_Creative_Code,
    #                                         Wave_1_OMD_Code_on_Mail,
    #                                         Wave_2_OMD,
    #                                         Wave_2_OMD_Creative_Code,
    #                                         Wave_2_OMD_Code_on_Mail,
    #                                         Wave_3_OMD,
    #                                         Wave_4_OMD_Creative_Code,
    #                                         Wave_4_OMD_Code_on_Mail,
    #                                         Wave_4_OMD,
    #                                         Wave_3_OMD_Creative_Code,
    #                                         Wave_3_OMD_Code_on_Mail,
    #                                         Wave_1_Mail,
    #                                         Wave_1_Mail_Creative_Code,
    #                                         Wave_1_Mail_Code_on_Mail,
    #                                         Wave_1_Email,
    #                                         Wave_1_Email_Creative_Code,
    #                                         Wave_1_Email_Code_on_Mail,
    #                                         Wave_1_Email_Deliverability_Indicator,
    #                                         Wave_1_Email_Open,
    #                                         Wave_1_Email_Click,
    #                                         Wave_2_Mail,
    #                                         Wave_2_Mail_Creative_Code,
    #                                         Wave_2_Mail_Code_on_Mail,
    #                                         Wave_2_Email,
    #                                         Wave_2_Email_Creative_Code,
    #                                         Wave_2_Email_Code_on_Mail,
    #                                         Wave_2_Email_Deliverability_Indicator,
    #                                         Wave_2_Email_Open,
    #                                         Wave_2_Email_Click,
    #                                         Wave_3_Mail,
    #                                         Wave_3_Mail_Creative_Code,
    #                                         Wave_3_Mail_Code_on_Mail,
    #                                         Wave_3_Email,
    #                                         Wave_3_Email_Creative_Code,
    #                                         Wave_3_Email_Code_on_Mail,
    #                                         Wave_3_Email_Deliverability_Indicator,
    #                                         Wave_3_Email_Open,
    #                                         Wave_3_Email_Click,
    #                                         Wave_4_Mail,
    #                                         Wave_4_Mail_Creative_Code,
    #                                         Wave_4_Mail_Code_on_Mail,
    #                                         Wave_4_Email,
    #                                         Wave_4_Email_Creative_Code,
    #                                         Wave_4_Email_Code_on_Mail,
    #                                         Wave_4_Email_Deliverability_Indicator,
    #                                         Wave_4_Email_Open,
    #                                         Wave_4_Email_Click,
    #                                         Wave_1_Social,
    #                                         Wave_1_Social_Creative_Code,
    #                                         Wave_1_Social_Code_on_Mail,
    #                                         Wave_2_Social,
    #                                         Wave_2_Social_Creative_Code,
    #                                         Wave_2_Social_Code_on_Mail,
    #                                         Wave_3_Social,
    #                                         Wave_3_Social_Creative_Code,
    #                                         Wave_3_Social_Code_on_Mail,
    #                                         Wave_4_Social,
    #                                         Wave_4_Social_Creative_Code,
    #                                         Wave_4_Social_Code_on_Mail,
    #                                         New_Customer_Match,
    #                                         Individual_Enterprise_ID,
    #                                         CE_Match_Level
    #                                     ) 
    #                                     VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,
    #                                     ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    #                 """ 
    #     conn.execute(query,l)
    #     print(i)